name: Release and Publish

on:
  push:
    branches:
      - main
      - alpha
      - beta
      - next

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: npm install
        run: npm install

      - name: npm lint
        run: npm run lint

      - name: npm types
        run: npm run types

      - name: npm build
        run: npm run build

      - name: npm test
        run: npm test

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: npm install
        run: npm install

      - name: npm types
        run: npm run types

      - name: npm build
        run: npm run build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release

      - name: Eik login and publish
        run: npx eik login -k $EIK_TOKEN && npx eik publish || true
        env:
          EIK_TOKEN: ${{ secrets.EIK_TOKEN }}
