name: Release
on:
  push:
    branches:
      - main
      - beta
      - next

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for trusted publishing and npm provenance
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24.x

      - run: npm clean-install
      - run: npm run lint
      - run: npm run types
      - run: npm run build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release

      - name: Eik login and publish
        run: npx eik login -k $EIK_TOKEN && npx eik publish || true
        env:
          EIK_TOKEN: ${{ secrets.EIK_TOKEN }}
